// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: loans.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLoan = `-- name: CreateLoan :one
INSERT INTO loans (movie_id, user_id, return_date)
VALUES ($1, $2, $3)
RETURNING id, movie_id, user_id, loan_date, return_date
`

type CreateLoanParams struct {
	MovieID    int32
	UserID     int32
	ReturnDate pgtype.Timestamp
}

func (q *Queries) CreateLoan(ctx context.Context, arg CreateLoanParams) (Loan, error) {
	row := q.db.QueryRow(ctx, createLoan, arg.MovieID, arg.UserID, arg.ReturnDate)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.UserID,
		&i.LoanDate,
		&i.ReturnDate,
	)
	return i, err
}

const getLoanByID = `-- name: GetLoanByID :one
SELECT id, movie_id, user_id, loan_date, return_date FROM loans
WHERE id = $1
`

func (q *Queries) GetLoanByID(ctx context.Context, id int32) (Loan, error) {
	row := q.db.QueryRow(ctx, getLoanByID, id)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.UserID,
		&i.LoanDate,
		&i.ReturnDate,
	)
	return i, err
}

const getMovieWithLoans = `-- name: GetMovieWithLoans :many
SELECT
    m.id AS movie_id,
    m.title,
    m.director,
    m.release_year,
    m.genre,
    m.available_copies,
    l.id AS loan_id,
    l.user_id,
    l.loan_date,
    l.return_date
FROM movies m
LEFT JOIN loans l ON l.movie_id = m.id
WHERE m.id = $1
ORDER BY l.id
`

type GetMovieWithLoansRow struct {
	MovieID         int32
	Title           string
	Director        string
	ReleaseYear     int32
	Genre           string
	AvailableCopies int32
	LoanID          pgtype.Int4
	UserID          pgtype.Int4
	LoanDate        pgtype.Timestamp
	ReturnDate      pgtype.Timestamp
}

func (q *Queries) GetMovieWithLoans(ctx context.Context, id int32) ([]GetMovieWithLoansRow, error) {
	rows, err := q.db.Query(ctx, getMovieWithLoans, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMovieWithLoansRow
	for rows.Next() {
		var i GetMovieWithLoansRow
		if err := rows.Scan(
			&i.MovieID,
			&i.Title,
			&i.Director,
			&i.ReleaseYear,
			&i.Genre,
			&i.AvailableCopies,
			&i.LoanID,
			&i.UserID,
			&i.LoanDate,
			&i.ReturnDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoans = `-- name: ListLoans :many
SELECT id, movie_id, user_id, loan_date, return_date FROM loans
ORDER BY id
`

func (q *Queries) ListLoans(ctx context.Context) ([]Loan, error) {
	rows, err := q.db.Query(ctx, listLoans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Loan
	for rows.Next() {
		var i Loan
		if err := rows.Scan(
			&i.ID,
			&i.MovieID,
			&i.UserID,
			&i.LoanDate,
			&i.ReturnDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoansByMovie = `-- name: ListLoansByMovie :many
SELECT id, movie_id, user_id, loan_date, return_date FROM loans
WHERE movie_id = $1
ORDER BY id
`

func (q *Queries) ListLoansByMovie(ctx context.Context, movieID int32) ([]Loan, error) {
	rows, err := q.db.Query(ctx, listLoansByMovie, movieID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Loan
	for rows.Next() {
		var i Loan
		if err := rows.Scan(
			&i.ID,
			&i.MovieID,
			&i.UserID,
			&i.LoanDate,
			&i.ReturnDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
