// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Loan struct {
	ID         int32
	MovieID    int32
	UserID     int32
	LoanDate   pgtype.Timestamp
	ReturnDate pgtype.Timestamp
}

type Movie struct {
	ID              int32
	Title           string
	Director        string
	ReleaseYear     int32
	Genre           string
	AvailableCopies int32
}

type User struct {
	ID    int32
	Name  string
	Email string
}
