// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: movies.sql

package database

import (
	"context"
)

const createMovie = `-- name: CreateMovie :one
INSERT INTO movies (title, director, release_year, genre, available_copies)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, title, director, release_year, genre, available_copies
`

type CreateMovieParams struct {
	Title           string
	Director        string
	ReleaseYear     int32
	Genre           string
	AvailableCopies int32
}

func (q *Queries) CreateMovie(ctx context.Context, arg CreateMovieParams) (Movie, error) {
	row := q.db.QueryRow(ctx, createMovie,
		arg.Title,
		arg.Director,
		arg.ReleaseYear,
		arg.Genre,
		arg.AvailableCopies,
	)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Director,
		&i.ReleaseYear,
		&i.Genre,
		&i.AvailableCopies,
	)
	return i, err
}

const deleteMovie = `-- name: DeleteMovie :exec
DELETE FROM movies
WHERE id = $1
`

func (q *Queries) DeleteMovie(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteMovie, id)
	return err
}

const getMovieByID = `-- name: GetMovieByID :one
SELECT id, title, director, release_year, genre, available_copies FROM movies
WHERE id = $1
`

func (q *Queries) GetMovieByID(ctx context.Context, id int32) (Movie, error) {
	row := q.db.QueryRow(ctx, getMovieByID, id)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Director,
		&i.ReleaseYear,
		&i.Genre,
		&i.AvailableCopies,
	)
	return i, err
}

const listMovies = `-- name: ListMovies :many
SELECT id, title, director, release_year, genre, available_copies FROM movies
ORDER BY id
`

func (q *Queries) ListMovies(ctx context.Context) ([]Movie, error) {
	rows, err := q.db.Query(ctx, listMovies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Movie
	for rows.Next() {
		var i Movie
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Director,
			&i.ReleaseYear,
			&i.Genre,
			&i.AvailableCopies,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMovie = `-- name: UpdateMovie :one
UPDATE movies
SET title = $2,
    director = $3,
    release_year = $4,
    genre = $5,
    available_copies = $6
WHERE id = $1
RETURNING id, title, director, release_year, genre, available_copies
`

type UpdateMovieParams struct {
	ID              int32
	Title           string
	Director        string
	ReleaseYear     int32
	Genre           string
	AvailableCopies int32
}

func (q *Queries) UpdateMovie(ctx context.Context, arg UpdateMovieParams) (Movie, error) {
	row := q.db.QueryRow(ctx, updateMovie,
		arg.ID,
		arg.Title,
		arg.Director,
		arg.ReleaseYear,
		arg.Genre,
		arg.AvailableCopies,
	)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Director,
		&i.ReleaseYear,
		&i.Genre,
		&i.AvailableCopies,
	)
	return i, err
}
